[palettes.colors]
dark_base = '#180038'
dark_main = '#27005a'
light_base = '#2c0085'
light_main = '#6114ff'
light_highlight = '#9753ff'
txt_main = '#9fa0ff'
txt_highlight = '#de66ff'
txt_sel = '#5454f4'
txt_dark = '#430db2'
txt_pale = '#6252A4'
txt_white = '#cfdfff'
txt_red = '#c62e60'
txt_orange = '#dF6350'
txt_yellow = '#FFB785'
txt_green = '#83edb6'
txt_cyan = '#82d4fC'
txt_blue = '#6287FC'
txt_purple = '#8351FC'
txt_pink = '#de66ff'