[mgr]
prepend_keymap = [
    { on = "S", run = "search --via=fd", desc = "Search files by name via fd" },
    { on = "s", run = 'shell "$SHELL" --block', desc = "Open shell here" },
    { on = [ "Y" ], run = '''
        shell 'dragon-drop -x -A "$@"' --confirm
    ''', desc = "dragon drop it!" },
    { on = [ "T" ], run = '''
        shell '$TERMINAL "$d" & disown' --confirm
    ''' },
    { on = "K", run = "arrow -4", desc = "Move cursor a tiny bit!" },
    { on = "J", run = "arrow 4", desc = "Move cursor a tiny bit!" },
]
