[mgr]
ratio = [2, 4, 4]
sort_by = "natural"
show_hidden = true
title_format = "Yazi: {cwd}"

[preview]
image_delay = 0
max_width = 1200
max_height = 1800


[opener]
edit = [
    { run = 'nvim "$1"', desc = "nvim", block = true},
]
pdf-open = [
    { run = '$BROWSER "$1"', desc = "$BROWSER", block = false},
]
play = [
    { run = 'mpv --force-window "$@"', orphan = true},
]
audio-open = [
    { run = 'mpv "$@"', for = "unix" },
]

[open]
rules = [
    # folder
    { name = "*/", use = [
        "edit",
        "open",
        "reveal",
    ] },
    # text
    { mime = "text/*", use = [
        "edit",
        "reveal",
    ] },
    # Pdf
    { mime = "application/pdf", use = [
        "pdf-open",
    ] }, 
    # Image
    { mime = "image/*", use = [
        "open",
        "reveal",
    ] },
    # Media
    { mime = "{video}/*", use = [
        "play",
        "reveal",
    ] },
    # Media
    { mime = "{audio}/*", use = [
        "audio-open",
        "reveal",
    ] },
    # Archive
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [
        "extract",
        "reveal",
    ] },
    # JSON
    { mime = "application/{json,ndjson}", use = [
        "edit",
        "reveal",
    ] },
    { mime = "*/javascript", use = [
        "edit",
        "reveal",
    ] },
    # Empty file
    { mime = "inode/empty", use = [
        "edit",
        "reveal",
    ] },
    # Fallback
    { name = "*", use = [
        "open",
        "reveal",
    ] },
]
